eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 9000
spring:
  application:
    name: lizk-zuul
zuul:
  routes:
#    testaaa:
#      serviceId: lizk-user
#      path: /testaaa/**
    api-order:
      path: /api-order/**
      serviceId: lizk-order
    api-user:
      path: /api-user/**
      serviceId: lizk-user
#  ignored-services: "*"
  # 前缀
#  prefix: /lizk